import Abby from './Abby.webp'
import Ashlee from './Ashlee.webp'
import Chris from './Chris.webp'
import Ivan from './Ivan.webp'
import Justin from './Justin.webp'
import Melanie from './Melanie.webp'
import RyanG from  './RyanG.webp'
import RyanX from './RyanX.webp'
import Saniya from './Saniya.webp'
import Tej from './Tej.webp'
import Tristan from './Tristan.webp'
import Anna from './Anna.webp'
import Roderick from './Roderick.webp'

export {Abby, Ashlee, Chris, Ivan, Justin, Melanie, RyanX, RyanG, Saniya, Tej, Tristan, Anna, Roderick}